"""
Script for processing images generated by curvatubes
    Input:
        - nii.gz source file
    Output:
        - The simulated density maps
        - The 3D reconstructed tomograms
        - Micrograph stacks
        - Polydata files
        - STAR file mapping particle coordinates and orientations with tomograms
"""

__author__ = 'Juan Diego Gallego Nicolas'

import sys
import csv
import time
import random
import scripts.data_gen.cvt_aux

import numpy as np
import nibabel as nib
from scipy.ndimage import distance_transform_edt

from polnet.lio import load_mrc, write_mrc
from polnet.utils import *
from scripts.data_gen.cvt_aux import gen_blyr_basic, gen_blyr_exp, reduce, gen_lyr

##### Input parameters

# Common tomogram settings
ROOT_PATH = os.path.realpath(os.getcwd() + '/../../data')

# Lists with the features to simulate

NII_LIST = ['bilayers coeffs [1 1 1 0 0 0] m -0.4.nii.gz',
             'exp 0366 coeffs [1 -0.238 11.988 -175.909 -27.167 2117.037] m -0.648.nii.gz',
             'exp 0374 coeffs [1 0.63 4.399 132.459 195.066 -2378.53] m -0.364.nii.gz',
             'tightlayers coeffs [3 3.741 11 -268 -4 6156] m -0.633.nii.gz',
             'exp 0868 coeffs [1 0.903 14.586 -57.566 -14.842 -1387.043] m -0.56.nii.gz']

# SOURCE FILES
SRC_DIR = os.path.realpath(ROOT_PATH + '/curvatubes_gallery')
os.makedirs(SRC_DIR, exist_ok=True)

# OUTPUT FILES
OUT_DIR = os.path.realpath(ROOT_PATH + '/curvatubes_mrc')
os.makedirs(OUT_DIR, exist_ok=True)

# Preparing intermediate directory
clean_dir(OUT_DIR)

# Save labels table
unit_lbl = 1
header_lbl_tab = ['MODEL', 'LABEL']
with open(OUT_DIR + '/labels_table.csv', 'w') as file_csv:
    writer_csv = csv.DictWriter(file_csv, fieldnames=header_lbl_tab, delimiter='\t')
    writer_csv.writeheader()
    for i in range(len(NII_LIST)):
        writer_csv.writerow({header_lbl_tab[0]:NII_LIST[i], header_lbl_tab[1]:unit_lbl})
        unit_lbl += 1

# In-out threshold
thr = 0.0         # Delimits the voxels enclosed by the membrane
vx_sz = 10        # Voxel size
layer_sep = 30  # Separation of the bilayer (armstrongs)
layer_th = 5   # Layer thickness (armstrongs)
sigma = 1         # Gaussian filter sigma

# Files loop
for p_id, p_file in enumerate(NII_LIST):

    print('\tPROCESSING FILE:', p_file)

    # Loading source nii.gz file
    ct_img = nib.load(SRC_DIR + '/' + p_file)
    ct_raw = np.array(ct_img.dataobj)
    write_mrc(ct_raw, fname=OUT_DIR + '/ct_' + str(p_id) + '_raw.mrc' , v_size=1)

    # Generating density map
    ct_den = np.copy(ct_raw)
    ct_den[ct_den>thr] = 1
    ct_den[ct_den<=thr] = 0
    write_mrc(ct_den, fname=OUT_DIR + '/ct_' + str(p_id) + '_den.mrc' , v_size=1)

    # Generation lyr
    ct_lyr = gen_lyr(ct_den, layer_th, vx_sz, sigma)
    write_mrc(ct_lyr, fname=OUT_DIR + '/ct_' + str(p_id) + '_lyr.mrc', v_size=1)

    # Generation blyr
    ct_blyr_bas = gen_blyr_basic(ct_den,layer_sep,layer_th, vx_sz,sigma)
    write_mrc(ct_blyr_bas, fname=OUT_DIR + '/ct_' + str(p_id) + '_blyr_bas.mrc', v_size=1)

    # Generation blyr expanded
    ct_blyr_exp = gen_blyr_exp(ct_den, layer_sep, layer_th, vx_sz*.5, sigma, 2)
    write_mrc(ct_blyr_exp, fname=OUT_DIR + '/ct_' + str(p_id) + '_blyr_exp.mrc', v_size=1)

    # Generation blyr expanded and reduced
    ct_bylr_alt = reduce(ct_blyr_exp,2)
    write_mrc(ct_bylr_alt, fname=OUT_DIR + '/ct_' + str(p_id) + '_blyr_alt.mrc', v_size=1)


print('Successfully terminated. (' + time.strftime("%c") + ')')